# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PrintDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'CocoaAsyncSocket', '~> 7.6.1'

  # Pods for PrintDemo

  target 'PrintDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PrintDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
